[workspace]
default-members = ["avbroot"]
members = ["avbroot", "e2e", "fuzz", "xtask"]
resolver = "2"

[workspace.package]
version = "2.3.2"
license = "GPL-3.0-only"
edition = "2021"
repository = "https://github.com/chenxiaolong/avbroot"
