name: Preload img cache
inputs:
  cache-key-prefix:
    description: 'Device cache-key prefix'
    required: true
  device:
    description: 'Device name'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache-img
      with:
        key: ${{ inputs.cache-key-prefix }}${{ inputs.device }}
        # Make sure any changes to path are also reflected in ci.yml setup
        path: e2e/files/${{ inputs.device }}-sparse.tar

    - if: ${{ steps.cache-img.outputs.cache-hit }}
      name: Extracting image from sparse archive
      shell: sh
      working-directory: e2e/files
      run: tar -xf ${{ inputs.device }}-sparse.tar

    - name: Restore e2e executable
      if: ${{ ! steps.cache-img.outputs.cache-hit }}
      uses: actions/cache/restore@v3
      with:
        key: e2e-${{ github.sha }}-${{ runner.os }}
        fail-on-cache-miss: true
        path: |
          target/release/e2e
          target/release/e2e.exe

    - name: Downloading device image for ${{ inputs.device }}
      if: ${{ ! steps.cache-img.outputs.cache-hit }}
      shell: sh
      working-directory: e2e
      run: ../target/release/e2e download --stripped -d ${{ inputs.device }}

    - if: ${{ ! steps.cache-img.outputs.cache-hit }}
      name: Creating sparse archive from image
      shell: sh
      working-directory: e2e/files
      run: |
        tar --sparse -cf ${{ inputs.device }}-sparse.tar \
          ${{ inputs.device }}/*.stripped
