---
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build modules
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # For git describe
          fetch-depth: 0

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo -n 'version=' >> "${GITHUB_OUTPUT}"
          git describe --always \
              | sed -E "s/^v//g;s/([^-]*-g)/r\1/;s/-/./g" \
              >> "${GITHUB_OUTPUT}"

      - name: Build modules
        run: cargo xtask modules -a

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: avbroot-modules-${{ steps.get_version.outputs.version }}
          path: modules/dist/
